<?php
/**
 * Plugin Name: WordPress MCP Manager
 * Description: Self-contained Streamable HTTP MCP server for securely managing WordPress from ChatGPT.
 * Version: 2.0.5
 * Requires at least: 6.5
 * Requires PHP: 8.0
 * Author: PageSurgeAI
 * License: GPL-2.0-or-later
 */
if (!defined('ABSPATH')) exit;

final class WPMCP_Manager {
 const NS='wpmcp/v1'; const VERSION='2.0.5'; const MCP_VERSION='2025-06-18';
 private static $instance;
 public static function instance(){return self::$instance ?: self::$instance=new self();}
 private function __construct(){add_action('rest_api_init',[$this,'routes']);add_action('admin_menu',[$this,'admin_menu']);add_action('admin_post_wpmcp_regenerate_token',[$this,'regenerate_token']);}
 public function routes(){
  register_rest_route(self::NS,'/site',['methods'=>'GET','callback'=>[$this,'site'],'permission_callback'=>[$this,'authenticated']]);
  register_rest_route(self::NS,'/capabilities',['methods'=>'GET','callback'=>[$this,'capabilities'],'permission_callback'=>[$this,'authenticated']]);
  register_rest_route(self::NS,'/execute',['methods'=>'POST','callback'=>[$this,'execute'],'permission_callback'=>[$this,'authenticated'],'args'=>['action'=>['required'=>true,'type'=>'string'],'confirm'=>['type'=>'boolean','default'=>false]]]);
  register_rest_route(self::NS,'/mcp',['methods'=>'POST','callback'=>[$this,'mcp'],'permission_callback'=>[$this,'mcp_authenticated']]);
 }
 public function authenticated(){return is_user_logged_in();}
 public function mcp_authenticated(){
  $origin=isset($_SERVER['HTTP_ORIGIN'])?esc_url_raw(wp_unslash($_SERVER['HTTP_ORIGIN'])):'';
  if($origin){$host=strtolower((string)wp_parse_url($origin,PHP_URL_HOST));$site=strtolower((string)wp_parse_url(home_url('/'),PHP_URL_HOST));$allowed=$host===$site||$host==='chatgpt.com'||str_ends_with($host,'.chatgpt.com')||$host==='openai.com'||str_ends_with($host,'.openai.com');if(!$allowed)return new WP_Error('invalid_origin','Origin is not allowed.',['status'=>403]);}
  $header=isset($_SERVER['HTTP_AUTHORIZATION'])?trim(wp_unslash($_SERVER['HTTP_AUTHORIZATION'])):'';
  if(!$header&&function_exists('getallheaders')){$h=getallheaders();$header=trim($h['Authorization']??$h['authorization']??'');}
  if(preg_match('/^Bearer\s+(.+)$/i',$header,$m)){$hash=(string)get_option('wpmcp_token_hash','');if($hash&&hash_equals($hash,hash('sha256',trim($m[1])))){$uid=(int)get_option('wpmcp_service_user',0);if($uid&&get_user_by('id',$uid)){wp_set_current_user($uid);return true;}}}
  return new WP_Error('unauthorized','A valid MCP bearer token is required.',['status'=>401]);
 }
 private function need($cap){if(!current_user_can($cap))return new WP_Error('forbidden','Your WordPress user lacks '.$cap.'.',['status'=>403]);return true;}
 private function confirmed($r,$label){if(!$r->get_param('confirm'))return new WP_Error('confirmation_required','Set confirm=true to '.$label.'.',['status'=>409]);return true;}
 private function ok($data=[]){return rest_ensure_response(array_merge(['success'=>true],$data));}
 private function input(WP_REST_Request $r){
  // Native REST requests arrive as JSON, while MCP tools/call creates an
  // internal request with body parameters. Support both transports so MCP
  // arguments are not discarded before reaching the action handler.
  $json=$r->get_json_params();
  if(is_array($json))return $json;
  $body=$r->get_body_params();
  return is_array($body)?$body:[];
 }
 public function site(){global $wp_version;return $this->ok(['name'=>get_bloginfo('name'),'url'=>home_url('/'),'admin_url'=>admin_url(),'wordpress_version'=>$wp_version,'php_version'=>PHP_VERSION,'plugin_version'=>self::VERSION,'active_theme'=>wp_get_theme()->get('Name'),'multisite'=>is_multisite(),'rest_url'=>rest_url(self::NS),'mcp_endpoint'=>rest_url(self::NS.'/mcp')]);}
 public function capabilities(){
  $actions=['content.list','content.get','content.create','content.update','content.trash','content.restore','content.delete','content.status','media.list','media.get','media.upload_base64','media.update','media.delete','terms.list','terms.create','terms.update','terms.delete','comments.list','comments.update','comments.delete','menus.list','menus.get','menus.create','menus.update','menus.delete','settings.get','settings.update','users.list','users.get','users.create','users.update','users.delete','themes.list','themes.install_base64','themes.activate','themes.delete','plugins.list','plugins.install_base64','plugins.activate','plugins.deactivate','plugins.delete','maintenance.flush_rewrite','maintenance.clear_object_cache'];
  return $this->ok(['actions'=>$actions,'safety'=>'Destructive and privileged actions require confirm=true and native WordPress capabilities.']);
 }
 public function execute(WP_REST_Request $r){
  $a=sanitize_text_field($r['action']);$map=[
   'content.list'=>'content_list','content.get'=>'content_get','content.create'=>'content_create','content.update'=>'content_update','content.trash'=>'content_trash','content.restore'=>'content_restore','content.delete'=>'content_delete','content.status'=>'content_status',
   'media.list'=>'media_list','media.get'=>'media_get','media.upload_base64'=>'media_upload','media.update'=>'media_update','media.delete'=>'media_delete',
   'terms.list'=>'terms_list','terms.create'=>'terms_create','terms.update'=>'terms_update','terms.delete'=>'terms_delete',
   'comments.list'=>'comments_list','comments.update'=>'comments_update','comments.delete'=>'comments_delete',
   'menus.list'=>'menus_list','menus.get'=>'menus_get','menus.create'=>'menus_create','menus.update'=>'menus_update','menus.delete'=>'menus_delete',
   'settings.get'=>'settings_get','settings.update'=>'settings_update','users.list'=>'users_list','users.get'=>'users_get','users.create'=>'users_create','users.update'=>'users_update','users.delete'=>'users_delete',
   'themes.list'=>'themes_list','themes.install_base64'=>'themes_install','themes.activate'=>'themes_activate','themes.delete'=>'themes_delete',
   'plugins.list'=>'plugins_list','plugins.install_base64'=>'plugins_install','plugins.activate'=>'plugins_activate','plugins.deactivate'=>'plugins_deactivate','plugins.delete'=>'plugins_delete',
   'maintenance.flush_rewrite'=>'flush_rewrite','maintenance.clear_object_cache'=>'clear_cache'];
  if(!isset($map[$a]))return new WP_Error('unknown_action','Unknown action. Call /capabilities for the supported list.',['status'=>400]);
  return $this->{$map[$a]}($r,$this->input($r));
 }
 private function post_type($p){$t=isset($p['post_type'])?sanitize_key($p['post_type']):'page';return post_type_exists($t)?$t:false;}
 private function content_list($r,$p){$c=$this->need('edit_posts');if(is_wp_error($c))return $c;$t=$this->post_type($p);if(!$t)return new WP_Error('bad_type','Invalid post type.',['status'=>400]);$q=new WP_Query(['post_type'=>$t,'post_status'=>isset($p['status'])?sanitize_key($p['status']):'any','posts_per_page'=>min(100,max(1,(int)($p['per_page']??20))),'paged'=>max(1,(int)($p['page']??1)),'s'=>sanitize_text_field($p['search']??''),'orderby'=>'modified','order'=>'DESC']);$items=array_map(fn($x)=>$this->post_data($x),$q->posts);return $this->ok(['items'=>$items,'total'=>(int)$q->found_posts,'pages'=>(int)$q->max_num_pages]);}
 private function content_get($r,$p){$id=(int)($p['id']??0);$post=get_post($id);if(!$post)return new WP_Error('not_found','Content not found.',['status'=>404]);$c=$this->need('edit_post');if(!current_user_can('edit_post',$id))return new WP_Error('forbidden','Cannot edit this item.',['status'=>403]);return $this->ok(['item'=>$this->post_data($post,true)]);}
 private function post_data($x,$full=false){$d=['id'=>$x->ID,'type'=>$x->post_type,'status'=>$x->post_status,'title'=>get_the_title($x),'slug'=>$x->post_name,'modified_gmt'=>$x->post_modified_gmt,'link'=>get_permalink($x)];if($full){$d['content']=$x->post_content;$d['excerpt']=$x->post_excerpt;$d['author']=(int)$x->post_author;$d['parent']=(int)$x->post_parent;$d['featured_media']=(int)get_post_thumbnail_id($x);$d['meta']=get_post_meta($x->ID);}return $d;}
 private function content_create($r,$p){$t=$this->post_type($p);if(!$t)return new WP_Error('bad_type','Invalid post type.',['status'=>400]);$cap=get_post_type_object($t)->cap->create_posts;$c=$this->need($cap);if(is_wp_error($c))return $c;$status=sanitize_key($p['status']??'draft');if($status==='publish'){if(!$r['confirm'])return new WP_Error('confirmation_required','Set confirm=true to publish.',['status'=>409]);if(!current_user_can(get_post_type_object($t)->cap->publish_posts))return new WP_Error('forbidden','Cannot publish this type.',['status'=>403]);}$id=wp_insert_post(['post_type'=>$t,'post_title'=>sanitize_text_field($p['title']??''),'post_content'=>wp_kses_post($p['content']??''),'post_excerpt'=>sanitize_textarea_field($p['excerpt']??''),'post_name'=>sanitize_title($p['slug']??''),'post_status'=>$status,'post_parent'=>(int)($p['parent']??0),'menu_order'=>(int)($p['menu_order']??0)],true);if(is_wp_error($id))return $id;$this->set_post_extras($id,$p);return $this->ok(['item'=>$this->post_data(get_post($id),true)]);}
 private function content_update($r,$p){$id=(int)($p['id']??0);if(!get_post($id))return new WP_Error('not_found','Content not found.',['status'=>404]);if(!current_user_can('edit_post',$id))return new WP_Error('forbidden','Cannot edit this item.',['status'=>403]);$fields=['ID'=>$id];$map=['title'=>'post_title','content'=>'post_content','excerpt'=>'post_excerpt','slug'=>'post_name','status'=>'post_status','parent'=>'post_parent','menu_order'=>'menu_order'];foreach($map as $k=>$v)if(array_key_exists($k,$p))$fields[$v]=in_array($k,['content'],true)?wp_kses_post($p[$k]):($k==='slug'?sanitize_title($p[$k]):(in_array($k,['parent','menu_order'],true)?(int)$p[$k]:sanitize_text_field($p[$k])));if(($fields['post_status']??'')==='publish'&&!$r['confirm'])return new WP_Error('confirmation_required','Set confirm=true to publish.',['status'=>409]);$res=wp_update_post($fields,true);if(is_wp_error($res))return $res;$this->set_post_extras($id,$p);return $this->ok(['item'=>$this->post_data(get_post($id),true)]);}
 private function set_post_extras($id,$p){if(isset($p['featured_media']))set_post_thumbnail($id,(int)$p['featured_media']);if(isset($p['terms'])&&is_array($p['terms']))foreach($p['terms'] as $tax=>$terms)if(taxonomy_exists($tax))wp_set_object_terms($id,array_map('intval',(array)$terms),$tax);if(isset($p['meta'])&&is_array($p['meta']))foreach($p['meta'] as $k=>$v)update_post_meta($id,sanitize_key($k),sanitize_text_field($v));}
 private function content_status($r,$p){return $this->content_update($r,['id'=>(int)($p['id']??0),'status'=>sanitize_key($p['status']??'draft')]);}
 private function content_trash($r,$p){$id=(int)($p['id']??0);if(!current_user_can('delete_post',$id))return new WP_Error('forbidden','Cannot trash this item.',['status'=>403]);$c=$this->confirmed($r,'move this content to Trash');if(is_wp_error($c))return $c;$x=wp_trash_post($id);return $x?$this->ok(['id'=>$id,'status'=>'trash']):new WP_Error('failed','Could not trash content.',['status'=>500]);}
 private function content_restore($r,$p){$id=(int)($p['id']??0);if(!current_user_can('delete_post',$id))return new WP_Error('forbidden','Cannot restore this item.',['status'=>403]);$c=$this->confirmed($r,'restore this content');if(is_wp_error($c))return $c;$x=wp_untrash_post($id);return $x?$this->ok(['item'=>$this->post_data($x)]):new WP_Error('failed','Could not restore content.',['status'=>500]);}
 private function content_delete($r,$p){$id=(int)($p['id']??0);if(!current_user_can('delete_post',$id))return new WP_Error('forbidden','Cannot delete this item.',['status'=>403]);$c=$this->confirmed($r,'permanently delete this content');if(is_wp_error($c))return $c;$x=wp_delete_post($id,true);return $x?$this->ok(['deleted_id'=>$id]):new WP_Error('failed','Could not delete content.',['status'=>500]);}
 private function media_list($r,$p){$c=$this->need('upload_files');if(is_wp_error($c))return $c;$q=new WP_Query(['post_type'=>'attachment','post_status'=>'inherit','posts_per_page'=>min(100,max(1,(int)($p['per_page']??20))),'paged'=>max(1,(int)($p['page']??1)),'s'=>sanitize_text_field($p['search']??'')]);return $this->ok(['items'=>array_map(fn($x)=>$this->media_data($x->ID),$q->posts),'total'=>(int)$q->found_posts]);}
 private function media_get($r,$p){$id=(int)($p['id']??0);if(!get_post($id))return new WP_Error('not_found','Media not found.',['status'=>404]);return $this->ok(['item'=>$this->media_data($id)]);}
 private function media_data($id){return ['id'=>$id,'title'=>get_the_title($id),'url'=>wp_get_attachment_url($id),'mime_type'=>get_post_mime_type($id),'alt'=>get_post_meta($id,'_wp_attachment_image_alt',true),'caption'=>wp_get_attachment_caption($id),'metadata'=>wp_get_attachment_metadata($id)];}
 private function media_upload($r,$p){$c=$this->need('upload_files');if(is_wp_error($c))return $c;$name=sanitize_file_name($p['filename']??'upload.bin');$raw=base64_decode((string)($p['base64']??''),true);if($raw===false||strlen($raw)>20*1024*1024)return new WP_Error('bad_upload','Invalid base64 or file exceeds 20 MB.',['status'=>400]);$up=wp_upload_bits($name,null,$raw);if($up['error'])return new WP_Error('upload_failed',$up['error'],['status'=>400]);require_once ABSPATH.'wp-admin/includes/image.php';$type=wp_check_filetype($up['file']);$id=wp_insert_attachment(['post_mime_type'=>$type['type'],'post_title'=>sanitize_text_field($p['title']??pathinfo($name,PATHINFO_FILENAME)),'post_status'=>'inherit'],$up['file']);wp_update_attachment_metadata($id,wp_generate_attachment_metadata($id,$up['file']));if(isset($p['alt']))update_post_meta($id,'_wp_attachment_image_alt',sanitize_text_field($p['alt']));return $this->ok(['item'=>$this->media_data($id)]);}
 private function media_update($r,$p){$id=(int)($p['id']??0);if(!current_user_can('edit_post',$id))return new WP_Error('forbidden','Cannot edit media.',['status'=>403]);$f=['ID'=>$id];if(isset($p['title']))$f['post_title']=sanitize_text_field($p['title']);if(isset($p['caption']))$f['post_excerpt']=sanitize_textarea_field($p['caption']);if(isset($p['description']))$f['post_content']=wp_kses_post($p['description']);$x=wp_update_post($f,true);if(is_wp_error($x))return $x;if(isset($p['alt']))update_post_meta($id,'_wp_attachment_image_alt',sanitize_text_field($p['alt']));return $this->ok(['item'=>$this->media_data($id)]);}
 private function media_delete($r,$p){$id=(int)($p['id']??0);if(!current_user_can('delete_post',$id))return new WP_Error('forbidden','Cannot delete media.',['status'=>403]);$c=$this->confirmed($r,'permanently delete this media file');if(is_wp_error($c))return $c;return wp_delete_attachment($id,true)?$this->ok(['deleted_id'=>$id]):new WP_Error('failed','Could not delete media.',['status'=>500]);}
 private function terms_list($r,$p){$tax=sanitize_key($p['taxonomy']??'category');if(!taxonomy_exists($tax))return new WP_Error('bad_taxonomy','Taxonomy not found.',['status'=>404]);$items=get_terms(['taxonomy'=>$tax,'hide_empty'=>false,'search'=>sanitize_text_field($p['search']??''),'number'=>min(100,max(0,(int)($p['per_page']??50)))]);return is_wp_error($items)?$items:$this->ok(['items'=>$items]);}
 private function terms_create($r,$p){$tax=sanitize_key($p['taxonomy']??'category');$obj=get_taxonomy($tax);if(!$obj||!current_user_can($obj->cap->manage_terms))return new WP_Error('forbidden','Cannot manage this taxonomy.',['status'=>403]);$x=wp_insert_term(sanitize_text_field($p['name']??''),$tax,['slug'=>sanitize_title($p['slug']??''),'description'=>sanitize_textarea_field($p['description']??''),'parent'=>(int)($p['parent']??0)]);return is_wp_error($x)?$x:$this->ok($x);}
 private function terms_update($r,$p){$tax=sanitize_key($p['taxonomy']??'category');$obj=get_taxonomy($tax);if(!$obj||!current_user_can($obj->cap->manage_terms))return new WP_Error('forbidden','Cannot manage this taxonomy.',['status'=>403]);$args=[];foreach(['name','slug','description'] as $k)if(isset($p[$k]))$args[$k]=$k==='slug'?sanitize_title($p[$k]):sanitize_text_field($p[$k]);if(isset($p['parent']))$args['parent']=(int)$p['parent'];$x=wp_update_term((int)($p['id']??0),$tax,$args);return is_wp_error($x)?$x:$this->ok($x);}
 private function terms_delete($r,$p){$tax=sanitize_key($p['taxonomy']??'category');$obj=get_taxonomy($tax);if(!$obj||!current_user_can($obj->cap->delete_terms))return new WP_Error('forbidden','Cannot delete terms.',['status'=>403]);$c=$this->confirmed($r,'delete this term');if(is_wp_error($c))return $c;$x=wp_delete_term((int)($p['id']??0),$tax);return is_wp_error($x)?$x:$this->ok(['deleted'=>(bool)$x]);}
 private function comments_list($r,$p){$c=$this->need('moderate_comments');if(is_wp_error($c))return $c;$q=new WP_Comment_Query;return $this->ok(['items'=>$q->query(['status'=>sanitize_key($p['status']??'all'),'number'=>min(100,max(1,(int)($p['per_page']??20))),'offset'=>max(0,(int)($p['offset']??0))])]);}
 private function comments_update($r,$p){$c=$this->need('moderate_comments');if(is_wp_error($c))return $c;$id=(int)($p['id']??0);$d=['comment_ID'=>$id];if(isset($p['content']))$d['comment_content']=wp_kses_post($p['content']);if(isset($p['status']))$d['comment_approved']=sanitize_key($p['status']);$x=wp_update_comment($d,true);return is_wp_error($x)?$x:$this->ok(['id'=>$id]);}
 private function comments_delete($r,$p){$c=$this->need('moderate_comments');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'delete this comment');if(is_wp_error($ok))return $ok;$id=(int)($p['id']??0);return wp_delete_comment($id,!empty($p['force']))?$this->ok(['deleted_id'=>$id]):new WP_Error('failed','Could not delete comment.',['status'=>500]);}
 private function menus_list($r,$p){$c=$this->need('edit_theme_options');if(is_wp_error($c))return $c;return $this->ok(['items'=>wp_get_nav_menus(),'locations'=>get_nav_menu_locations(),'registered_locations'=>get_registered_nav_menus()]);}
 private function menus_get($r,$p){$c=$this->need('edit_theme_options');if(is_wp_error($c))return $c;$id=(int)($p['id']??0);return $this->ok(['menu'=>wp_get_nav_menu_object($id),'items'=>wp_get_nav_menu_items($id)]);}
 private function menus_create($r,$p){$c=$this->need('edit_theme_options');if(is_wp_error($c))return $c;$id=wp_create_nav_menu(sanitize_text_field($p['name']??''));if(is_wp_error($id))return $id;if(!empty($p['location'])){$loc=get_theme_mod('nav_menu_locations',[]);$loc[sanitize_key($p['location'])]=$id;set_theme_mod('nav_menu_locations',$loc);}return $this->ok(['id'=>$id]);}
 private function menus_update($r,$p){$c=$this->need('edit_theme_options');if(is_wp_error($c))return $c;$id=(int)($p['menu_id']??0);if(!empty($p['name']))wp_update_nav_menu_object($id,['menu-name'=>sanitize_text_field($p['name'])]);if(isset($p['item'])&&is_array($p['item'])){$i=$p['item'];$item_id=wp_update_nav_menu_item($id,(int)($i['id']??0),['menu-item-title'=>sanitize_text_field($i['title']??''),'menu-item-url'=>esc_url_raw($i['url']??''),'menu-item-object-id'=>(int)($i['object_id']??0),'menu-item-object'=>sanitize_key($i['object']??'custom'),'menu-item-type'=>sanitize_key($i['type']??'custom'),'menu-item-status'=>'publish','menu-item-parent-id'=>(int)($i['parent']??0),'menu-item-position'=>(int)($i['position']??0)]);if(is_wp_error($item_id))return $item_id;}return $this->menus_get($r,['id'=>$id]);}
 private function menus_delete($r,$p){$c=$this->need('edit_theme_options');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'delete this menu');if(is_wp_error($ok))return $ok;$x=wp_delete_nav_menu((int)($p['id']??0));return is_wp_error($x)?$x:$this->ok(['deleted'=>true]);}
 private function settings_get($r,$p){$c=$this->need('manage_options');if(is_wp_error($c))return $c;$keys=['blogname','blogdescription','admin_email','timezone_string','date_format','time_format','start_of_week','show_on_front','page_on_front','page_for_posts','posts_per_page','default_comment_status','permalink_structure'];$d=[];foreach($keys as $k)$d[$k]=get_option($k);return $this->ok(['settings'=>$d]);}
 private function settings_update($r,$p){$c=$this->need('manage_options');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'change site settings');if(is_wp_error($ok))return $ok;$allowed=['blogname','blogdescription','admin_email','timezone_string','date_format','time_format','start_of_week','show_on_front','page_on_front','page_for_posts','posts_per_page','default_comment_status','permalink_structure'];$done=[];foreach(($p['settings']??[]) as $k=>$v)if(in_array($k,$allowed,true)){update_option($k,is_string($v)?sanitize_text_field($v):(int)$v);$done[]=$k;}if(in_array('permalink_structure',$done,true))flush_rewrite_rules();return $this->ok(['updated'=>$done]);}
 private function users_list($r,$p){$c=$this->need('list_users');if(is_wp_error($c))return $c;$users=get_users(['number'=>min(100,max(1,(int)($p['per_page']??20))),'search'=>sanitize_text_field($p['search']??'')]);return $this->ok(['items'=>array_map(fn($u)=>['id'=>$u->ID,'login'=>$u->user_login,'name'=>$u->display_name,'email'=>$u->user_email,'roles'=>$u->roles],$users)]);}
 private function users_get($r,$p){$c=$this->need('list_users');if(is_wp_error($c))return $c;$u=get_userdata((int)($p['id']??0));return $u?$this->ok(['item'=>['id'=>$u->ID,'login'=>$u->user_login,'name'=>$u->display_name,'email'=>$u->user_email,'roles'=>$u->roles]]):new WP_Error('not_found','User not found.',['status'=>404]);}
 private function users_create($r,$p){$c=$this->need('create_users');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'create this user');if(is_wp_error($ok))return $ok;$id=wp_insert_user(['user_login'=>sanitize_user($p['login']??''),'user_email'=>sanitize_email($p['email']??''),'user_pass'=>(string)($p['password']??wp_generate_password(24,true,true)),'display_name'=>sanitize_text_field($p['name']??''),'role'=>sanitize_key($p['role']??get_option('default_role'))]);return is_wp_error($id)?$id:$this->ok(['id'=>$id]);}
 private function users_update($r,$p){$id=(int)($p['id']??0);if(!current_user_can('edit_user',$id))return new WP_Error('forbidden','Cannot edit this user.',['status'=>403]);$ok=$this->confirmed($r,'change this user');if(is_wp_error($ok))return $ok;$d=['ID'=>$id];foreach(['user_email'=>'email','display_name'=>'name','user_pass'=>'password','role'=>'role'] as $field=>$key)if(isset($p[$key]))$d[$field]=$key==='email'?sanitize_email($p[$key]):($key==='role'?sanitize_key($p[$key]):sanitize_text_field($p[$key]));$x=wp_update_user($d);return is_wp_error($x)?$x:$this->ok(['id'=>$id]);}
 private function users_delete($r,$p){$id=(int)($p['id']??0);if(!current_user_can('delete_user',$id))return new WP_Error('forbidden','Cannot delete this user.',['status'=>403]);if($id===get_current_user_id())return new WP_Error('self_delete_blocked','Self-deletion is blocked.',['status'=>409]);$ok=$this->confirmed($r,'permanently delete this user');if(is_wp_error($ok))return $ok;require_once ABSPATH.'wp-admin/includes/user.php';return wp_delete_user($id,(int)($p['reassign']??0))?$this->ok(['deleted_id'=>$id]):new WP_Error('failed','Could not delete user.',['status'=>500]);}
 private function themes_list($r,$p){$c=$this->need('switch_themes');if(is_wp_error($c))return $c;$active=wp_get_theme();$items=[];foreach(wp_get_themes() as $slug=>$t)$items[]=['slug'=>$slug,'name'=>$t->get('Name'),'version'=>$t->get('Version'),'active'=>$active->get_stylesheet()===$slug];return $this->ok(['items'=>$items]);}
 private function write_zip($p,$kind){$raw=base64_decode((string)($p['base64_zip']??''),true);if($raw===false||strlen($raw)>30*1024*1024)return new WP_Error('bad_archive','Invalid base64 or archive exceeds 30 MB.',['status'=>400]);if(strlen($raw)<4||substr($raw,0,2)!=='PK')return new WP_Error('bad_archive','The uploaded data is not a ZIP archive.',['status'=>400]);require_once ABSPATH.'wp-admin/includes/file.php';$file=wp_tempnam(sanitize_file_name($p['filename']??$kind.'.zip'));if(!$file||file_put_contents($file,$raw)===false)return new WP_Error('write_failed','Could not write temporary archive.',['status'=>500]);return $file;}
 private function install_zip($file,$kind,$force=false){
  if(!class_exists('ZipArchive'))return new WP_Error('zip_unavailable','PHP ZipArchive is required for remote package installation.',['status'=>500]);
  $zip=new ZipArchive();$opened=$zip->open($file);
  if($opened!==true)return new WP_Error('bad_archive','WordPress could not open the ZIP archive.',['status'=>400,'zip_error'=>$opened]);
  $root='';$invalid=false;
  for($i=0;$i<$zip->numFiles;$i++){
   $stat=$zip->statIndex($i);$name=str_replace('\\','/',$stat['name']??'');
   if($name===''||str_contains($name,"\0")||str_starts_with($name,'/')||preg_match('#^[A-Za-z]:/#',$name)||preg_match('#(^|/)\.\.(/|$)#',$name)){$invalid=true;break;}
   $parts=explode('/',trim($name,'/'));$top=$parts[0]??'';
   if($top===''||($root!==''&&$top!==$root)){$invalid=true;break;}$root=$top;
   if($zip->getExternalAttributesIndex($i,$opsys,$attr)&&((($attr>>16)&0170000)===0120000)){$invalid=true;break;}
  }
  if($invalid||$root===''||sanitize_file_name($root)!==$root){$zip->close();return new WP_Error('unsafe_archive','ZIP must contain one safely named top-level folder and no traversal paths or symbolic links.',['status'=>400]);}
  $base=$kind==='theme'?get_theme_root():WP_PLUGIN_DIR;$target=trailingslashit($base).$root;
  if(file_exists($target)&&!$force){$zip->close();return new WP_Error('destination_exists',ucfirst($kind).' already exists; pass force=true to replace it.',['status'=>409,'slug'=>$root]);}
  if(file_exists($target)&&$force){
   require_once ABSPATH.'wp-admin/includes/file.php';
   global $wp_filesystem;if(!WP_Filesystem()||!$wp_filesystem){$zip->close();return new WP_Error('filesystem_unavailable','WordPress filesystem access is unavailable.',['status'=>500]);}
   if(!$wp_filesystem->delete($target,true)){$zip->close();return new WP_Error('replace_failed','Could not remove the existing package.',['status'=>500]);}
  }
  $done=$zip->extractTo($base);$zip->close();
  if(!$done||!is_dir($target))return new WP_Error('extract_failed','Could not extract the package into WordPress.',['status'=>500]);
  if($kind==='theme'){wp_clean_themes_cache(true);$theme=wp_get_theme($root);if(!$theme->exists())return new WP_Error('invalid_theme','The extracted package is not a valid WordPress theme.',['status'=>400]);return $this->ok(['installed'=>true,'theme'=>$root]);}
  require_once ABSPATH.'wp-admin/includes/plugin.php';wp_clean_plugins_cache(true);$plugins=get_plugins('/'.$root);if(!$plugins)return new WP_Error('invalid_plugin','The extracted package contains no valid WordPress plugin.',['status'=>400]);return $this->ok(['installed'=>true,'plugin'=>$root.'/'.array_key_first($plugins)]);
 }
 private function write_theme_file($p){
  $slug=sanitize_key($p['stylesheet']??'');$relative=str_replace('\\','/',(string)($p['filename']??''));
  if($slug===''||$slug!==($p['stylesheet']??''))return new WP_Error('bad_theme_slug','A safe lowercase stylesheet slug is required.',['status'=>400]);
  if($relative===''||str_contains($relative,"\0")||str_starts_with($relative,'/')||preg_match('#^[A-Za-z]:/#',$relative)||preg_match('#(^|/)\.\.(/|$)#',$relative))return new WP_Error('unsafe_path','Theme file path is unsafe.',['status'=>400]);
  $allowed=['php','css','js','json','txt','md','png','jpg','jpeg','gif','webp','svg','woff','woff2'];$ext=strtolower(pathinfo($relative,PATHINFO_EXTENSION));
  if(!in_array($ext,$allowed,true))return new WP_Error('file_type_blocked','This theme file type is not allowed.',['status'=>400]);
  $raw=base64_decode((string)($p['base64_zip']??''),true);
  if($raw===false||strlen($raw)>10*1024*1024)return new WP_Error('bad_upload','Invalid base64 or theme file exceeds 10 MB.',['status'=>400]);
  $root=trailingslashit(get_theme_root()).$slug;$target=trailingslashit($root).$relative;$parent=dirname($target);
  if(!is_dir($parent)&&!wp_mkdir_p($parent))return new WP_Error('mkdir_failed','Could not create the theme directory.',['status'=>500]);
  if(file_exists($target)&&empty($p['force']))return new WP_Error('destination_exists','Theme file already exists; pass force=true to replace it.',['status'=>409]);
  require_once ABSPATH.'wp-admin/includes/file.php';$tmp=wp_tempnam(basename($target));if(!$tmp||file_put_contents($tmp,$raw,LOCK_EX)===false)return new WP_Error('write_failed','Could not write the temporary theme file.',['status'=>500]);
  if(!@rename($tmp,$target)){if(!@copy($tmp,$target)){@unlink($tmp);return new WP_Error('move_failed','Could not move the theme file into place.',['status'=>500]);}@unlink($tmp);}
  @chmod($target,0644);clearstatcache(true,$target);
  if(!is_file($target)||filesize($target)!==strlen($raw))return new WP_Error('verify_failed','Theme file verification failed.',['status'=>500]);
  require_once ABSPATH.'wp-admin/includes/theme.php';wp_clean_themes_cache(true);return $this->ok(['uploaded'=>true,'theme'=>$slug,'file'=>$relative,'bytes'=>strlen($raw)]);
 }
 private function themes_install($r,$p){$c=$this->need('install_themes');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'install this theme');if(is_wp_error($ok))return $ok;if(!empty($p['stylesheet'])&&!empty($p['filename'])&&!str_ends_with(strtolower($p['filename']),'.zip'))return $this->write_theme_file($p);$file=$this->write_zip($p,'theme');if(is_wp_error($file))return $file;try{$x=$this->install_zip($file,'theme',!empty($p['force']));}catch(Throwable $e){$x=new WP_Error('installer_exception','Theme installer error: '.$e->getMessage(),['status'=>500]);}@unlink($file);return $x;}
 private function themes_activate($r,$p){$c=$this->need('switch_themes');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'activate this theme');if(is_wp_error($ok))return $ok;$slug=sanitize_text_field($p['stylesheet']??'');$t=wp_get_theme($slug);if(!$t->exists())return new WP_Error('not_found','Theme not found.',['status'=>404]);switch_theme($slug);return $this->ok(['active_theme'=>wp_get_theme()->get('Name')]);}
 private function themes_delete($r,$p){$c=$this->need('delete_themes');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'permanently delete this theme');if(is_wp_error($ok))return $ok;require_once ABSPATH.'wp-admin/includes/theme.php';$x=delete_theme(sanitize_text_field($p['stylesheet']??''));return is_wp_error($x)?$x:$this->ok(['deleted'=>true]);}
 private function plugins_list($r,$p){$c=$this->need('activate_plugins');if(is_wp_error($c))return $c;require_once ABSPATH.'wp-admin/includes/plugin.php';$items=[];foreach(get_plugins() as $file=>$d)$items[]=['file'=>$file,'name'=>$d['Name'],'version'=>$d['Version'],'active'=>is_plugin_active($file)];return $this->ok(['items'=>$items]);}
 private function plugins_install($r,$p){$c=$this->need('install_plugins');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'install this plugin');if(is_wp_error($ok))return $ok;$file=$this->write_zip($p,'plugin');if(is_wp_error($file))return $file;try{$x=$this->install_zip($file,'plugin',!empty($p['force']));}catch(Throwable $e){$x=new WP_Error('installer_exception','Plugin installer error: '.$e->getMessage(),['status'=>500]);}@unlink($file);return $x;}
 private function plugins_activate($r,$p){$c=$this->need('activate_plugins');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'activate this plugin');if(is_wp_error($ok))return $ok;require_once ABSPATH.'wp-admin/includes/plugin.php';$file=plugin_basename($p['plugin']??'');$x=activate_plugin($file);return is_wp_error($x)?$x:$this->ok(['plugin'=>$file,'active'=>true]);}
 private function plugins_deactivate($r,$p){$c=$this->need('activate_plugins');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'deactivate this plugin');if(is_wp_error($ok))return $ok;require_once ABSPATH.'wp-admin/includes/plugin.php';$file=plugin_basename($p['plugin']??'');if($file===plugin_basename(__FILE__))return new WP_Error('self_deactivate_blocked','Remote self-deactivation is blocked.',['status'=>409]);deactivate_plugins($file);return $this->ok(['plugin'=>$file,'active'=>false]);}
 private function plugins_delete($r,$p){$c=$this->need('delete_plugins');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'permanently delete this plugin');if(is_wp_error($ok))return $ok;require_once ABSPATH.'wp-admin/includes/plugin.php';$file=plugin_basename($p['plugin']??'');if($file===plugin_basename(__FILE__))return new WP_Error('self_delete_blocked','Remote self-deletion is blocked.',['status'=>409]);$x=delete_plugins([$file]);return is_wp_error($x)?$x:$this->ok(['deleted'=>true]);}
 private function flush_rewrite($r,$p){$c=$this->need('manage_options');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'flush permalink rules');if(is_wp_error($ok))return $ok;flush_rewrite_rules(false);return $this->ok(['flushed'=>true]);}
 private function clear_cache($r,$p){$c=$this->need('manage_options');if(is_wp_error($c))return $c;$ok=$this->confirmed($r,'clear the object cache');if(is_wp_error($ok))return $ok;return $this->ok(['flushed'=>(bool)wp_cache_flush()]);}

 private function action_names(){return ['content.list','content.get','content.create','content.update','content.trash','content.restore','content.delete','content.status','media.list','media.get','media.upload_base64','media.update','media.delete','terms.list','terms.create','terms.update','terms.delete','comments.list','comments.update','comments.delete','menus.list','menus.get','menus.create','menus.update','menus.delete','settings.get','settings.update','users.list','users.get','users.create','users.update','users.delete','themes.list','themes.install_base64','themes.activate','themes.delete','plugins.list','plugins.install_base64','plugins.activate','plugins.deactivate','plugins.delete','maintenance.flush_rewrite','maintenance.clear_object_cache'];}
 private function tool_schema(){return ['type'=>'object','properties'=>[
  'confirm'=>['type'=>'boolean','description'=>'Required and true for publishing, deletion, installation, activation, user changes, settings changes, and maintenance.'],
  'id'=>['type'=>'integer'],'post_type'=>['type'=>'string','description'=>'Usually post or page.'],'status'=>['type'=>'string'],'title'=>['type'=>'string'],'content'=>['type'=>'string'],'excerpt'=>['type'=>'string'],'slug'=>['type'=>'string'],'search'=>['type'=>'string'],'per_page'=>['type'=>'integer','minimum'=>1,'maximum'=>100],'page'=>['type'=>'integer','minimum'=>1],'parent'=>['type'=>'integer'],'menu_order'=>['type'=>'integer'],'featured_media'=>['type'=>'integer'],'terms'=>['type'=>'object'],'meta'=>['type'=>'object'],'taxonomy'=>['type'=>'string'],'name'=>['type'=>'string'],'description'=>['type'=>'string'],'menu_id'=>['type'=>'integer'],'location'=>['type'=>'string'],'item'=>['type'=>'object'],'settings'=>['type'=>'object'],'login'=>['type'=>'string'],'email'=>['type'=>'string'],'password'=>['type'=>'string'],'role'=>['type'=>'string'],'reassign'=>['type'=>'integer'],'filename'=>['type'=>'string'],'base64'=>['type'=>'string'],'base64_zip'=>['type'=>'string'],'alt'=>['type'=>'string'],'caption'=>['type'=>'string'],'stylesheet'=>['type'=>'string'],'plugin'=>['type'=>'string'],'force'=>['type'=>'boolean']
 ],'additionalProperties'=>true];}
 private function tools(){
  $empty_schema=['type'=>'object','properties'=>(object)[],'additionalProperties'=>false];
  $tools=[['name'=>'get_site_info','description'=>'Read WordPress site identity, versions, active theme, URLs, and connection status.','inputSchema'=>$empty_schema,'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false]],['name'=>'list_wordpress_capabilities','description'=>'List all WordPress management actions supported by this server.','inputSchema'=>$empty_schema,'annotations'=>['readOnlyHint'=>true,'destructiveHint'=>false]]];
  foreach($this->action_names() as $a){$read=str_ends_with($a,'.list')||str_ends_with($a,'.get');$danger=str_contains($a,'delete')||str_contains($a,'install')||str_contains($a,'activate')||str_contains($a,'deactivate')||str_contains($a,'trash')||str_contains($a,'restore')||str_contains($a,'settings.update')||str_contains($a,'maintenance');$tools[]=['name'=>str_replace('.','_',$a),'description'=>ucfirst(str_replace(['.','_'],[' ',' '],$a)).'. Use exact IDs from a prior read. Consequential changes require confirm=true.','inputSchema'=>$this->tool_schema(),'annotations'=>['readOnlyHint'=>$read,'destructiveHint'=>$danger,'idempotentHint'=>$read]];}
  return $tools;
 }
 private function rpc_error($id,$code,$message,$data=null){$e=['jsonrpc'=>'2.0','id'=>$id,'error'=>['code'=>$code,'message'=>$message]];if($data!==null)$e['error']['data']=$data;return new WP_REST_Response($e,200,['Content-Type'=>'application/json']);}
 private function rpc_result($id,$result){return new WP_REST_Response(['jsonrpc'=>'2.0','id'=>$id,'result'=>$result],200,['Content-Type'=>'application/json','MCP-Protocol-Version'=>self::MCP_VERSION]);}
 public function mcp(WP_REST_Request $r){
  $b=$r->get_json_params();if(!is_array($b)||($b['jsonrpc']??'')!=='2.0')return $this->rpc_error($b['id']??null,-32600,'Invalid Request');$id=$b['id']??null;$method=(string)($b['method']??'');
  if(str_starts_with($method,'notifications/'))return new WP_REST_Response(null,202);
  if($method==='initialize')return $this->rpc_result($id,['protocolVersion'=>self::MCP_VERSION,'capabilities'=>['tools'=>['listChanged'=>false]],'serverInfo'=>['name'=>'wordpress-mcp-manager','version'=>self::VERSION],'instructions'=>'Read before writing. Use IDs and modified values from reads. Ask the user before consequential actions and pass confirm=true only after approval.']);
  if($method==='ping')return $this->rpc_result($id,(object)[]);
  if($method==='tools/list')return $this->rpc_result($id,['tools'=>$this->tools()]);
  if($method==='tools/call')return $this->mcp_call($id,$b['params']??[]);
  return $this->rpc_error($id,-32601,'Method not found');
 }
 private function mcp_call($id,$params){
  $name=sanitize_key($params['name']??'');$args=is_array($params['arguments']??null)?$params['arguments']:[];
  if($name==='get_site_info')$response=$this->site();elseif($name==='list_wordpress_capabilities')$response=$this->capabilities();else{$lookup=[];foreach($this->action_names() as $a)$lookup[str_replace('.','_',$a)]=$a;if(!isset($lookup[$name]))return $this->rpc_error($id,-32602,'Unknown tool');$args['action']=$lookup[$name];$req=new WP_REST_Request('POST','/'.self::NS.'/execute');$req->set_body_params($args);$response=$this->execute($req);}
  if(is_wp_error($response)){$payload=['code'=>$response->get_error_code(),'message'=>$response->get_error_message(),'data'=>$response->get_error_data()];return $this->rpc_result($id,['content'=>[['type'=>'text','text'=>wp_json_encode($payload)]],'isError'=>true,'structuredContent'=>$payload]);}
  $data=$response instanceof WP_REST_Response?$response->get_data():$response;$json=wp_json_encode($data,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);return $this->rpc_result($id,['content'=>[['type'=>'text','text'=>$json]],'structuredContent'=>$data]);
 }
 public function admin_menu(){add_options_page('WordPress MCP Manager','WordPress MCP','manage_options','wpmcp-manager',[$this,'settings_page']);}
 public function regenerate_token(){if(!current_user_can('manage_options'))wp_die('Forbidden');check_admin_referer('wpmcp_regenerate_token');$token='wpmcp_'.wp_generate_password(48,false,false);update_option('wpmcp_token_hash',hash('sha256',$token),false);update_option('wpmcp_service_user',get_current_user_id(),false);set_transient('wpmcp_new_token_'.get_current_user_id(),$token,5*MINUTE_IN_SECONDS);wp_safe_redirect(admin_url('options-general.php?page=wpmcp-manager&generated=1'));exit;}
 public function settings_page(){if(!current_user_can('manage_options'))return;$token=get_transient('wpmcp_new_token_'.get_current_user_id());if($token)delete_transient('wpmcp_new_token_'.get_current_user_id());$service=get_userdata((int)get_option('wpmcp_service_user',get_current_user_id()));?>
  <div class="wrap"><h1>WordPress MCP Manager</h1><p>Connect ChatGPT to this MCP endpoint:</p><p><code style="font-size:14px"><?php echo esc_html(rest_url(self::NS.'/mcp')); ?></code></p><?php if($token): ?><div class="notice notice-warning inline"><p><strong>Copy this bearer token now. It will not be shown again.</strong></p><p><input type="text" readonly value="<?php echo esc_attr($token); ?>" style="width:100%;max-width:760px" onclick="this.select()"></p></div><?php endif; ?><p>The token acts with the permissions of: <strong><?php echo esc_html($service?$service->user_login:'not configured'); ?></strong></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="wpmcp_regenerate_token"><?php wp_nonce_field('wpmcp_regenerate_token'); ?><?php submit_button(get_option('wpmcp_token_hash')?'Regenerate bearer token':'Generate bearer token','primary'); ?></form><p>Regenerating immediately invalidates the previous token.</p></div>
 <?php }
}
WPMCP_Manager::instance();
register_activation_hook(__FILE__,function(){if(!get_option('wpmcp_service_user'))update_option('wpmcp_service_user',get_current_user_id(),false);});
